use studentdb;

SELECT * FROM students;

SELECT AVG(grade) as AVG_of_student_grade FROM students;

SELECT MAX(grade) as MAX_of_student_grade FROM STUDENTS;

SELECT MIN(GRADE) as MIN_OF_STUDENT_GRADE FROM STUDENTS;

SELECT COUNT(GRADE) as COUNT_OF_STUDENT_GRADE FROM STUDENTS;

SELECT AVG(grade) FROM STUDENTS  WHERE classroom=101 OR CLASSROOM= 102;

SELECT CLASSROOM, MAX(GRADE) FROM STUDENTS GROUP BY CLASSROOM;

SELECT CLASSROOM, MIN(GRADE) FROM STUDENTS GROUP BY CLASSROOM;

SELECT CLASSROOM,COUNT(CLASSROOM)FROM STUDENTS GROUP BY CLASSROOM DESC;

SELECT CLASSROOM,AVG(GRADE)FROM STUDENTS GROUP BY CLASSROOM;

SELECT CLASSROOM, MAX(GRADE)FROM STUDENTS GROUP BY CLASSROOM DESC;

SELECT CLASSROOM,MIN(GRADE) FROM STUDENTS GROUP BY CLASSROOM DESC;

